development:
  adapter: postgresql
  encoding: unicode
  database: fantasia_dev
  pool: 5
  username: admin

test:
  adapter: postgresql
  encoding: unicode
  database: fantasia_test
  pool: 5
  username: booth_checkin

production:
  adapter: postgresql
  encoding: unicode
  database: fantasia_production
  pool: 5
  username: admin
